configure_modules() {
    log "Unloading conflicting modules..."
    for mod in "${CONFLICTING_MODS[@]}"; do
        if lsmod | grep -q "^$mod"; then
            modprobe -r "$mod" 2>/dev/null || warn "Could not unload $mod"
        fi
    done

    log "Updating blacklist..."
    {
        echo "# Generated by installer.sh"
        for mod in "${CONFLICTING_MODS[@]}"; do
            echo "blacklist $mod"
        done
    } > "$BLACKLIST_FILE"
}